stages:
  - build
  - test

variables:
  GIT_STRATEGY: none
  MalterlibDeployRoot: "${CI_PROJECT_DIR}/Deploy"
  MalterlibRepositoryHardReset: "true"
  MalterlibPreBuildNoClean: "true"
  MalterlibDisableBuildSystemGeneration: "true"
  MalterlibEnableLinkTimeCodeGeneration: "false"
  MalterlibBuildLogFile: "Artifacts/Build.log"
  ASAN_OPTIONS: "detect_leaks=0"
  TSAN_OPTIONS: "second_deadlock_stack=1"
  EnablePlatform_Linux2_6: "true"
  MalterlibEnableInternalTests: "true"
  RunningCI: "true"

before_script:
  - 'set -e'
  - 'if [[ ! -d "${CI_PROJECT_DIR}/.git" ]]; then'
  - '  echo "Initializing: ${CI_PROJECT_DIR}"'
  - '  mkdir -p "${CI_PROJECT_DIR}"'
  - '  pushd "${CI_PROJECT_DIR}" > /dev/null'
  - '  git init .'
  - '  popd > /dev/null'
  - 'fi'
  - 'pushd "${CI_PROJECT_DIR}" > /dev/null'
  - 'echo "Fetching in \"${CI_PROJECT_DIR}\""'
  - 'export GIT_TERMINAL_PROMPT=0'
  - 'if ! git remote add origin "${CI_REPOSITORY_URL}" 2> /dev/null; then'
  - '  git remote set-url origin "${CI_REPOSITORY_URL}"'
  - 'fi'
  - 'git fetch origin --prune'
  - 'popd > /dev/null'
  - 'git checkout -f -B "$CI_COMMIT_REF_NAME" "$CI_COMMIT_SHA"'
  - 'git clean -fd'

Build_Linux:
  stage: build
  tags:
    - OSX
    - Build
  script:
    - set -e
    - ./mib update_repos
    - rm -rf Deploy
    - mkdir -p BuildSystem/Default
    - echo "DefaultRoot \"${MalterlibDeployRoot}\"" > BuildSystem/Default/PostCopy.MConfig
    - ./mib prebuild Malterlib Tests
    - ./mib build Tests Linux2.6 x64 Debug
    - GZIP=-1 tar -czf Artifacts/Deploy.tar.gz Deploy
  artifacts:
    when: always
    name: "Tests"
    expire_in: 1 day
    paths:
      - Artifacts/Deploy.tar.gz
      - Artifacts/Build.log

Build_Linux_ReleaseTesting:
  stage: build
  tags:
    - OSX
    - Build
  script:
    - set -e
    - ./mib update_repos
    - rm -rf Deploy
    - mkdir -p BuildSystem/Default
    - echo "DefaultRoot \"${MalterlibDeployRoot}\"" > BuildSystem/Default/PostCopy.MConfig
    - ./mib prebuild Malterlib Tests
    - ./mib build Tests Linux2.6 x64 "Release Testing (Tests)"
    - GZIP=-1 tar -czf Artifacts/Deploy_ReleaseTesting.tar.gz Deploy
  artifacts:
    when: always
    name: "Tests Release Testing"
    expire_in: 1 day
    paths:
      - Artifacts/Deploy_ReleaseTesting.tar.gz
      - Artifacts/Build.log

Build_Linux_Release:
  stage: build
  tags:
    - OSX
    - Build
  script:
    - set -e
    - ./mib update_repos
    - rm -rf Deploy
    - mkdir -p BuildSystem/Default
    - echo "DefaultRoot \"${MalterlibDeployRoot}\"" > BuildSystem/Default/PostCopy.MConfig
    - ./mib prebuild Malterlib Tests
    - ./mib build Tests Linux2.6 x64 "Release (Tests)"
    - GZIP=-1 tar -czf Artifacts/Deploy_Release.tar.gz Deploy
  artifacts:
    when: always
    name: "Tests Release"
    expire_in: 1 day
    paths:
      - Artifacts/Deploy_Release.tar.gz
      - Artifacts/Build.log

Build_Linux_Release_TSan:
  stage: build
  tags:
    - OSX
    - Build
  variables:
    MalterlibSupportSanitizerEnable_Thread: "true"
  script:
    - set -e
    - ./mib update_repos
    - rm -rf Deploy
    - mkdir -p BuildSystem/Default
    - echo "DefaultRoot \"${MalterlibDeployRoot}\"" > BuildSystem/Default/PostCopy.MConfig
    - ./mib prebuild Malterlib Tests
    - ./mib build Tests Linux2.6 x64 "Release (Tests)"
    - GZIP=-1 tar -czf Artifacts/Deploy_Release_TSan.tar.gz Deploy
  artifacts:
    when: always
    name: "Tests Release (TSan)"
    expire_in: 1 day
    paths:
      - Artifacts/Deploy_Release_TSan.tar.gz
      - Artifacts/Build.log

Build_Linux_Release_ASan:
  stage: build
  tags:
    - OSX
    - Build
  variables:
    MalterlibSupportSanitizerEnable_Address: "true"
  script:
    - set -e
    - ./mib update_repos
    - rm -rf Deploy
    - mkdir -p BuildSystem/Default
    - echo "DefaultRoot \"${MalterlibDeployRoot}\"" > BuildSystem/Default/PostCopy.MConfig
    - ./mib prebuild Malterlib Tests
    - ./mib build Tests Linux2.6 x64 "Release (Tests)"
    - GZIP=-1 tar -czf Artifacts/Deploy_Release_ASan.tar.gz Deploy
  artifacts:
    when: always
    name: "Tests Release (ASan)"
    expire_in: 1 day
    paths:
      - Artifacts/Deploy_Release_ASan.tar.gz
      - Artifacts/Build.log

Build_Linux_Release_UBSan:
  stage: build
  tags:
    - OSX
    - Build
  variables:
    MalterlibSupportSanitizerEnable_UndefinedBehavior: "true"
  script:
    - set -e
    - ./mib update_repos
    - rm -rf Deploy
    - mkdir -p BuildSystem/Default
    - echo "DefaultRoot \"${MalterlibDeployRoot}\"" > BuildSystem/Default/PostCopy.MConfig
    - ./mib prebuild Malterlib Tests
    - ./mib build Tests Linux2.6 x64 "Release (Tests)"
    - GZIP=-1 tar -czf Artifacts/Deploy_Release_UBSan.tar.gz Deploy
  artifacts:
    when: always
    name: "Tests Release (UBSan)"
    expire_in: 1 day
    paths:
      - Artifacts/Deploy_Release_UBSan.tar.gz
      - Artifacts/Build.log

Test_Linux:
  stage: test
  needs: ["Build_Linux"]
  tags:
    - LinuxHighMem
  dependencies:
    - Build_Linux
  before_script:
    - echo Skipping git sync
  script:
    - set -e
    - rm -rf Deploy
    - tar -xf Artifacts/Deploy.tar.gz
    - pushd Deploy/Tests_Linux_x64
    - ./RunAllTests --no-quiet
    - popd

Test_Linux_ReleaseTesting:
  stage: test
  needs: ["Build_Linux_ReleaseTesting"]
  tags:
    - LinuxHighMem
  dependencies:
    - Build_Linux_ReleaseTesting
  before_script:
    - echo Skipping git sync
  script:
    - set -e
    - rm -rf Deploy
    - tar -xf Artifacts/Deploy_ReleaseTesting.tar.gz
    - pushd Deploy/Tests_Linux_x64
    - ./RunAllTests --no-quiet
    - popd

Test_Linux_Release:
  stage: test
  needs: ["Build_Linux_Release"]
  tags:
    - LinuxHighMem
  dependencies:
    - Build_Linux_Release
  before_script:
    - echo Skipping git sync
  script:
    - set -e
    - rm -rf Deploy
    - tar -xf Artifacts/Deploy_Release.tar.gz
    - pushd Deploy/Tests_Linux_x64
    - ./RunAllTests --quiet
    - popd

Test_Linux_Release_TSan:
  stage: test
  needs: ["Build_Linux_Release_TSan"]
  tags:
    - LinuxHighMem
  dependencies:
    - Build_Linux_Release_TSan
  before_script:
    - echo Skipping git sync
  script:
    - set -e
    - rm -rf Deploy
    - tar -xf Artifacts/Deploy_Release_TSan.tar.gz
    - pushd Deploy/Tests_Linux_x64
    - ./RunAllTests --no-quiet --no-parallel
    - popd

Test_Linux_Release_ASan:
  stage: test
  needs: ["Build_Linux_Release_ASan"]
  tags:
    - LinuxHighMem
  dependencies:
    - Build_Linux_Release_ASan
  before_script:
    - echo Skipping git sync
  script:
    - set -e
    - rm -rf Deploy
    - tar -xf Artifacts/Deploy_Release_ASan.tar.gz
    - pushd Deploy/Tests_Linux_x64
    - ./RunAllTests --no-quiet --no-parallel
    - popd

Test_Linux_Release_UBSan:
  stage: test
  needs: ["Build_Linux_Release_UBSan"]
  tags:
    - LinuxHighMem
  dependencies:
    - Build_Linux_Release_UBSan
  before_script:
    - echo Skipping git sync
  script:
    - set -e
    - rm -rf Deploy
    - tar -xf Artifacts/Deploy_Release_UBSan.tar.gz
    - pushd Deploy/Tests_Linux_x64
    - ./RunAllTests --no-quiet --no-parallel
    - popd

Clean:
  stage: build
  when: manual
  tags:
    - OSX
    - Build
  script:
    - ./mib postbuild Tests
