version = 1

[[annotations]]
path = ["ImportCache/**", "**/ImportCache/**", "IC/**", "**/IC/**", "**.MRepo", ".gitignore", "**/.gitignore", "**.md", ".claude/**.json", ".vscode/**.json", ".ignore", ".rgignore", "Malterlib.sublime-project"]
precedence = "override"
SPDX-FileCopyrightText = "Unbroken AB"
SPDX-License-Identifier = "Apache-2.0 WITH LLVM-exception"
