name: Test macOS

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      architecture:
        required: true
        type: string
      configuration:
        required: true
        type: string

env:
  Malterlib_UseCachedEnvironment: "false"
  Malterlib_UseUserSettings: "false"
  MalterlibRepositoryHardReset: "true"
  MalterlibPreBuildNoClean: "true"
  MalterlibPreBuildNoReBuild: "true"
  MalterlibDisableBuildSystemGeneration: "true"
  MalterlibEnableLinkTimeCodeGeneration: "false"
  MalterlibImportUpdateCache: "false"
  MalterlibBuildLogFile: "Artifacts/Build.log"
  MalterlibEnableSanitizerReleaseConfigs: "true"
  MalterlibEnablePrefTestConfig: "false"
  MalterlibEnableInternalTests: "true"
  MalterlibDebugSymbolsEnable: "false"
  MalterlibDeploySymbols: "false"
  MalterlibSupportCrashDumps: "false"
  MalterlibFlakySuites: "Malterlib/File/File/Tests;Malterlib/Process/ProcessLaunchFeatures/Run As;Malterlib/Time/Time/Time speed"
  MalterlibFlakyErrors: "Timed out waiting for user/group change to come into effect"
  MalterlibFileLineOnDebugBreak: "true"
  MalterlibReproducibleBuild: "true"
  MalterlibLogCategoryWidth: "60"
  MalterlibEnableBreakpad: "true"
  MalterlibConcurrency_DebugSubscriptions: "true"
  RunningCI: "true"
  MALTERLIB_GITHUB_USER_TOKEN: ${{ secrets.MALTERLIB_GITHUB_USER_TOKEN }}
  MALTERLIB_GITHUB_USER: ${{ secrets.MALTERLIB_GITHUB_USER }}
  ASAN_OPTIONS: "detect_leaks=0"
  TSAN_OPTIONS: "second_deadlock_stack=1"
  UBSAN_OPTIONS: "halt_on_error=1"

jobs:
  build_mac:
    name: Build ${{ inputs.platform }} ${{ inputs.architecture }} ${{ inputs.configuration }}
    runs-on: self-hosted-mac-build-x64
    timeout-minutes: 120
    env:
      BuildPlatform: ${{ inputs.platform }}
      BuildArchitecture: ${{ inputs.architecture }}
      BuildConfiguration: ${{ inputs.configuration }}
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: 'true'
        clean: false
        persist-credentials: false
    - name: Build
      shell: bash
      run: |
        set -e
        ./.github/workflows/Build.sh
    - uses: actions/upload-artifact@v4
      if: (failure() || success())
      with:
        name: Tests ${{ inputs.platform }} ${{ inputs.architecture }} ${{ inputs.configuration }}
        path: Artifacts

  test_mac:
    name: Test ${{ matrix.os }} ${{ inputs.architecture }} ${{ inputs.configuration }}
    runs-on: ${{ matrix.os }}
    needs: [build_mac]
    timeout-minutes: 70
    strategy:
      fail-fast: false
      matrix:
        #os: [macos-11, macos-12, macos-13, macos-14]
        os: [self-hosted-macos-11, self-hosted-macos-12, self-hosted-macos-13, self-hosted-macos-14, self-hosted-macos-15, self-hosted-macos-26]
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: Tests ${{ inputs.platform }} ${{ inputs.architecture }} ${{ inputs.configuration }}
        path: Artifacts
    - name: Run tests
      shell: bash
      run: |
        if ! which gtar; then
          brew install gnu-tar --quiet
        fi
        if ! which zstd; then
          brew install zstd --quiet
        fi
        if ! which node; then
          brew install node --quiet
        fi
        if ! which npm; then
          brew install npm --quiet
        fi
        pwd
        echo Num CPU threads: `getconf _NPROCESSORS_ONLN`
        ArtifactsPath="$PWD/Artifacts/Deploy.tar.zst"
        sudo rm -rf /opt/Deploy
        sudo mkdir -p /opt/Deploy
        sudo chown $USER /opt/Deploy
        cd /opt/Deploy
        export MalterlibCrashDumpDir="$PWD/CrashDumps"
        gtar -xf "$ArtifactsPath"
        TestsDirName=`find Tests* -maxdepth 0`
        if [[ "$TestsDirName" != "Tests" ]]; then
          mv "$TestsDirName" Tests
        fi
        cd Tests
        ./RunAllTests --quiet --launch-per-suite --suite-order slow_first --timeout 3600 -- --logs
        sudo -E ./RunAllTests -g SuperUser --quiet --launch-per-suite --suite-order slow_first --timeout 3600 --no-parallel -- --logs
        exit 0
