name: Test Linux

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      architecture:
        required: true
        type: string
      configuration:
        required: true
        type: string

env:
  Malterlib_UseCachedEnvironment: "false"
  Malterlib_UseUserSettings: "false"
  MalterlibRepositoryHardReset: "true"
  MalterlibPreBuildNoClean: "true"
  MalterlibDisableBuildSystemGeneration: "true"
  MalterlibEnableLinkTimeCodeGeneration: "false"
  MalterlibImportUpdateCache: "false"
  MalterlibBuildLogFile: "Artifacts/Build.log"
  MalterlibEnableSanitizerReleaseConfigs: "true"
  MalterlibEnablePrefTestConfig: "false"
  MalterlibEnableInternalTests: "true"
  MalterlibDebugSymbolsEnable: "false"
  MalterlibDeploySymbols: "false"
  MalterlibSupportCrashDumps: "false"
  MalterlibFlakySuites: "Malterlib/File/File/Tests"
  MalterlibFileLineOnDebugBreak: "true"
  MalterlibReproducibleBuild: "true"
  RunningCI: "true"
  MALTERLIB_GITHUB_USER_TOKEN: ${{ secrets.MALTERLIB_GITHUB_USER_TOKEN }}
  MALTERLIB_GITHUB_USER: ${{ secrets.MALTERLIB_GITHUB_USER }}
  ASAN_OPTIONS: "detect_leaks=0"
  TSAN_OPTIONS: "second_deadlock_stack=1"
  UBSAN_OPTIONS: "halt_on_error=1"

jobs:
  build_linux:
    name: Build ${{ inputs.platform }} ${{ inputs.architecture }} ${{ inputs.configuration }}
    runs-on: self-hosted-mac-build-x64
    timeout-minutes: 120
    env:
      BuildPlatform: ${{ inputs.platform }}
      BuildArchitecture: ${{ inputs.architecture }}
      BuildConfiguration: ${{ inputs.configuration }}
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: 'true'
        clean: false
        persist-credentials: false
    - name: Build
      shell: bash
      run: |
        set -e
        ./.github/workflows/Build.sh
    - uses: actions/upload-artifact@v4
      if: (failure() || success())
      with:
        name: Tests ${{ inputs.platform }} ${{ inputs.architecture }} ${{ inputs.configuration }}
        path: Artifacts

  test_linux:
    name: Test ${{ matrix.os }} ${{ inputs.architecture }} ${{ inputs.configuration }}
    runs-on: ${{ matrix.os }}
    needs: [build_linux]
    timeout-minutes: 70
    strategy:
      fail-fast: false
      matrix:
        #os: [ubuntu-20.04, ubuntu-22.04]
        os: [ubuntu-20.04]
    steps:
    - name: Maximize disk space
      shell: bash
      run: |
        df -h
        sudo rm -rf /usr/share/dotnet /opt/ghc /opt/hostedtoolcache/CodeQL
        df -h
    - uses: actions/download-artifact@v4
      with:
        name: Tests ${{ inputs.platform }} ${{ inputs.architecture }} ${{ inputs.configuration }}
        path: Artifacts
    - name: Swap space report before modification
      shell: bash
      run: |
        echo "Memory and swap:"
        df -h
        free -h
        echo
        swapon --show
        echo
    - name: Set Swap
      shell: bash
      run: |
          export SWAP_FILE=$(swapon --show=NAME | tail -n 1)
          sudo swapoff $SWAP_FILE
          sudo rm $SWAP_FILE
          sudo fallocate -l 12G $SWAP_FILE
          sudo chmod 600 $SWAP_FILE
          sudo mkswap $SWAP_FILE
          sudo swapon $SWAP_FILE
          export EXTRA_SWAP_FILE=/extra.swap
          sudo fallocate -l 8G $EXTRA_SWAP_FILE
          sudo chmod 600 $EXTRA_SWAP_FILE
          sudo mkswap $EXTRA_SWAP_FILE
          sudo swapon $EXTRA_SWAP_FILE

    - name: Swap space report after modification
      shell: bash
      run: |
        echo "Memory and swap:"
        df -h
        free -h
        echo
        swapon --show
        echo

    - name: Cleanup unneeded software
      shell: bash
      run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force

    - name: Free space after removing software
      shell: bash
      run: |
        echo "Memory and swap:"
        df -h
        free -h
        echo

    - name: Run tests
      shell: bash
      run: |
        pwd
        loginctl enable-linger runner
        sleep 1
        echo $XDG_RUNTIME_DIR
        export XDG_RUNTIME_DIR=/run/user/$UID
        echo $XDG_RUNTIME_DIR
        env
        ps aux --forest
        systemctl status || true
        echo Num CPU threads: `getconf _NPROCESSORS_ONLN`
        rm -rf Deploy
        mkdir -p Deploy
        cd Deploy
        tar -xf ../Artifacts/Deploy.tar.zst
        cd Tests*
        ./RunAllTests --quiet --launch-per-suite --suite-order slow_first --timeout 3600 -- --logs
        exit 0
